
const {MYWALLET,MYPROFILE,UPDATEPROFILE,LB,AVATARLIST,SHOPLIST,NOTICELIST,MAILLIST,MAILREAD,BANNERLIST } = require("./dashboard");
const {ADDCARD,GETCARD,WITHDRAWALREQ} = require("./updateWallet");
const {reconnect} = require("./reconnect")


module.exports = {
  MYPROFILE:MYPROFILE,
  UPDATEPROFILE:UPDATEPROFILE,
  MYWALLET:MYWALLET,
  LB:LB,
  AVATARLIST:AVATARLIST,
  SHOPLIST:SHOPLIST,
  NOTICELIST:NOTICELIST,
  MAILLIST:MAILLIST,
  MAILREAD:MAILREAD,
  ADDCARD:ADDCARD,
  reconnect: reconnect,
  GETCARD:GETCARD,
  WITHDRAWALREQ:WITHDRAWALREQ,
  BANNERLIST:BANNERLIST
};
